[package]
name = "demo"
version = "0.1.0"
edition = "2021"
authors = ["SF-Zhou <sfzhou.scut@gmail.com>"]

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
